practice2/my_app/urls.py
from my_app import views
from django.urls import path

app_name = 'my_app'

urlpatterns = [
    path('index/', views.index, name='index'),
    path('register/', views.register, name='register'),
]

practice2/practice2/urls.py
from django.contrib import admin
from django.urls import path,include
from my_app import views

urlpatterns = [
    path('', views.index, name='index'),

    path('admin/', admin.site.urls),
    path('my_app/', include('my_app.urls')),
]

practice2/my_app/models.py
from django.db import models
from django.contrib.auth.models import User

class UserprofileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    # additional fields

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(blank=True,upload_to='profile_pic_folder')

    def __str__(self):
        return self.user.username

practice2/my_app/forms.py
from django import forms
from django.contrib.auth.models import User
from my_app.models import UserprofileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserprofileInfo
        fields = ('portfolio_site','profile_pic')

practice2/my_app/views.py
from django.shortcuts import render
from my_app.forms import UserForm,UserProfileInfoForm



# Extra Imports for the Login and Logout Capabilities
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.urls import reverse

# Create your views here.
def index(request):
    return render(request,'my_app/index.html')

@login_required
def special(request):
    # Remember to also set login url in settings.py!
    # LOGIN_URL = '/basic_app/user_login/'
    return HttpResponse("You are logged in. Nice!")

@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == 'POST':

        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        # Check to see both forms are valid
        if user_form.is_valid() and profile_form.is_valid():

            # Save User Form to Database
            user = user_form.save()

            # Hash the password
            user.set_password(user.password)

            # Update with Hashed password
            user.save()

            # Now we deal with the extra info!

            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)

            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user

            # Check if they provided a profile picture
            if 'profile_pic' in request.FILES:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']

            # Now save model
            profile.save()

            # Registration Successful!
            registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'my_app/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})

def user_login(request):

    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request,user)
                # Send the user back to some page.
                # In this case their homepage.
                return HttpResponseRedirect(reverse('index'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        #Nothing has been provided for username or password.
        return render(request, 'my_app/login.html', {})

practice2/templates/my_app/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body>
    <nav class = "navbar-default">
        <div class = "container">
            <ul class = "nav navbar-nav">
                <li><a class = "navbar-brand" href="{% url 'index' %}">Django</a></li>
                <li><a class = "navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li><a class = "navbar-link" href="{% url 'my_app:register' %}">Registration</a></li>
            </ul>
        </div>
    </nav>
    <div class = "container">
        {% block my_block %}
        <h1>This is base.html</h1>
        {% endblock %}
    </div>
</body>
</html>

practice2/templates/my_app/index.html
{% extends "my_app/base.html" %}
{% block my_block %}

<div class = "container">
    <h1>Hello this is index page</h1>
</div>

{% endblock %}

practice2/templates/my_app/login.html
{% extends "my_app/base.html" %}
{% block body_block %}
<h1>Please! Log-in here</h1>
<form action="{% url'my_app:user_login' %}" method = "post">
    {% csrf_token %}
    <label for="Username">Username</label>
    <input type="text" name="" placeholder="Username">
    <label for="Email">E-mail</label>
    <input type="email" name="" >
    <label for="Password">Password</label>
    <input type="text" name="" id="">
    <input type="submit" name="" value="Log-in">

</form>
{% endblock %}

practice2/templates/my_app/registration.html
{% extends "my_app/base.html" %}
{% load static %}
{% block my_block %}
<h1>This is Registration Page</h1>
{% if registered %}
<h1>Thanks For Registering!</h1>
{% else %}
<h1>Register Here!</h1>
<h2>Fill-out this form:</h2>
<form enctype="multipart/form-data" method = "post">
    {{ user_form.as_p }}
    {{ profile_form.as_p }}
    {% csrf_token %}
    <input type="submit" name="" value="Submit">
</form>
{% endif %}
{% endblock %}